include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: ignore
    depend_on_referenced_packages: ignore
    file_names: ignore
    todo: ignore
    unnecessary_overrides: ignore
